dist: xenial

language: python

python:
  - "3.7"

services: mongodb

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python manage.py test

after_success:
  - codecov
